---
- name: playbook to prep networksetup for aws account
  hosts: localhost
  remote_user: testuser
  gather_facts: false

  vars_files:
    #- ../vars/info.yml
    - ../../info.yml

  tasks:
  ###### start VPC and network component setup ######

    #creating vpc for the ec2 hosts
    - name: create vpc for hosts
      ec2_vpc_net:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: test_vpc_net
        cidr_block: 10.0.0.0/16
        tags:
          module: ec2_vpc_net
        tenancy: default
      register: ansibleVPC

    - name: display ansibleVPC output
      debug:
        var: ansibleVPC

    #creating subnets for the ec2 hosts
    - name: create subnet for {{ ansibleVPC.vpc.id }}
      ec2_vpc_subnet:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        cidr: 10.0.0.0/16
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        map_public: yes
        tags:
          Name: public_subnet
      register: public_subnet

    - name: display public_subnet output
      debug:
        var: public_subnet
      
    #creating igw for the inernet access for ec2 hosts
    - name: create igw for {{ ansibleVPC.vpc.id }}
      ec2_vpc_igw: 
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        tags:
          Name: ansibleVPC_IGW
      register: ansibleVPC_IGW

    - name: display ansibleVPC_IGW output
      debug:
        var: ansibleVPC_IGW

    #creating route table for associating internet route to IGW
    - name: create routetable for {{ public_subnet.subnet.id }}
      ec2_vpc_route_table: 
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        tags:
          Name: rt_ansibleVPC_PublicSubnet
        subnets:
          - "{{ public_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansibleVPC_IGW.gateway_id }}"
      register: rt_ansibleVPC_PublicSubnet

    - name: display rt_ansibleVPC_PublicSubnet output
      debug:
        var: rt_ansibleVPC_PublicSubnet

    #creating security groups for ssh access to ec2 hosts
    - name: create security for ssh access
      ec2_group: 
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: "test security group"
        description: "test security group"
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        tags:
          Name: rt_ansibleVPC_PublicSubnet
        rules:
          - proto: "tcp"
            ports: "22"
            cidr_ip: 0.0.0.0/0
      register: my_vpc_sg

    - name: display my_vpc_sg output
      debug:
        var: my_vpc_sg

  ###### end VPC and network component setup ######


  ###### start EC2 Deployment ######

    - name: find redhat amis
      ec2_ami_info:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        owner: 309956199498 #redhat owenrID
        filters:
          architecture: x86_64
          name: RHEL-8*HVM-*
      register: amis

    - name: display the amis output
      debug:
        var: amis



    


    





    


         
        


