---
- name: playbook to prep networksetup for aws account
  hosts: localhost
  remote_user: testuser
  gather_facts: false

  vars_files:
    #- ../vars/info.yml
    - ../../info.yml

  tasks:
    #creating vpc for the ec2 hosts
    - name: create vpc for hosts
      amazon.aws.ec2_vpc_net:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: test_vpc_net
        cidr_block: 10.0.0.0/16
        tags:
          module: ec2_vpc_net
        tenancy: default
      register: ansibleVPC

    - name: display ansibleVPC output
      debug:
        var: ansibleVPC

    #creating subnets for the ec2 hosts
    - name: create igw for {{ ansibleVPC.vpc.id }}
      amazon.aws.ec2_vpc_subnet:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        cidr: 10.0.0.0/16
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        map_public: yes
        tags:
          Name: public_subnet
      register: public_subnet

    - name: display public_subnet output
      debug:
        var: public_subnet
      
    #creating igw for the inernet access for ec2 hosts
    - name: create IGW for {{ ansibleVPC.vpc.id }}
      amazon.aws.ec2_vpc_igw: 
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        tags:
          Name: ansibleVPC_IGW
      register: ansibleVPC_IGW

    - name: display ansibleVPC_IGW
      debug:
        var: ansibleVPC_IGW





    


         
        


