---
- name: playbook to prep networksetup for aws account
  hosts: all
  remote_user: ec2-user
  gather_facts: false

  vars_files:
    #- ../vars/info.yml
    - ../../info.yml

  tasks:
    - name: terminate ec2 instances
      hosts: localhost
      connection: local
      tasks:
        - name: terminate ec2 instance
          debug:
            var: {{ aws_key }}