---
- name: playbook to prep networksetup for aws account
  hosts: all
  remote_user: testuser
  gather_facts: true

  vars_files:
    #- ../vars/info.yml
    - ../../info.yml

  tasks:
    - name: current Instance InstanceId
      debug:
        vars: instance_id
      
    - name: terminate ec2 instance {{ instance_id }}
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: "absent"
        instance_id: "{{ instance_id }}"